apiVersion: v1
kind: Pod
metadata:
  name: kiada
spec:
  shareProcessNamespace: true
  initContainers:
    - name: init-demo
      image: luksa/init-demo:0.1
    - name: traffic-logger
      image: luksa/network-traffic-meter:0.1
      restartPolicy: Always
    - name: ping
      image: luksa/network-connectivity-checker:0.1

  containers:
    - name: kiada
      image: luksa/kiada:0.1
      ports:
        - containerPort: 8080
          name: http
      startupProbe:
        httpGet:
          port: http
          path: /
        periodSeconds: 10
        failureThreshold: 120
      livenessProbe:
        httpGet:
          port: http
          path: /
        periodSeconds: 5
        failureThreshold: 2

    - name: envoy
      image: luksa/kiada-ssl-proxy:0.1
      ports:
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 9901
      livenessProbe:
        exec:
          command:
            - /usr/bin/env true
        httpGet:
          port: admin
          path: /ready
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
